name: Docker image

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Build image
        run: docker build --tag "$IMAGE_NAME:latest" --tag "$IMAGE_NAME:$GITHUB_SHA" .
      - name: Push image
        run: docker push --all-tags "$IMAGE_NAME"
